### ISSUE TITLE
CML language server fails to start

### ISSUE THREAD

**Issue by francoisvdv** [ContextMapper/vscode-extension#41]
Hi,

I am unable to try the VS Code extension because of the following error. This shows up in the "CML Language Server" output in the VS Code output window.

```
[Error - 3:00:03 PM] Client CML Language Server: connection to server is erroring.
Message header must separate key and value using ':'

Shutting down server.
[Error - 3:00:03 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (c:\Users\userxyz\.vscode\extensions\contextmapper.context-mapper-vscode-extension-6.12.0\node_modules\vscode-languageclient\lib\common\client.js:964:19)
	at LanguageClient.stop (c:\Users\userxyz\.vscode\extensions\contextmapper.context-mapper-vscode-extension-6.12.0\node_modules\vscode-languageclient\lib\common\client.js:935:21)
	at LanguageClient.stop (c:\Users\userxyz\.vscode\extensions\contextmapper.context-mapper-vscode-extension-6.12.0\node_modules\vscode-languageclient\lib\node\main.js:150:22)
	at LanguageClient.handleConnectionError (c:\Users\userxyz\.vscode\extensions\contextmapper.context-mapper-vscode-extension-6.12.0\node_modules\vscode-languageclient\lib\common\client.js:1196:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 3:00:03 PM] Server process exited with code 1.
[Error - 3:00:03 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 3:00:03 PM] Connection to server got closed. Server will restart.
true
[Error - 3:00:03 PM] CML Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:00:04 PM] Client CML Language Server: connection to server is erroring.
Message header must separate key and value using ':'

Shutting down server.
[Error - 3:00:04 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at LanguageClient.shutdown (c:\Users\userxyz\.vscode\extensions\contextmapper.context-mapper-vscode-extension-6.12.0\node_modules\vscode-languageclient\lib\common\client.js:964:19)
	at LanguageClient.stop (c:\Users\userxyz\.vscode\extensions\contextmapper.context-mapper-vscode-extension-6.12.0\node_modules\vscode-languageclient\lib\common\client.js:935:21)
	at LanguageClient.stop (c:\Users\userxyz\.vscode\extensions\contextmapper.context-mapper-vscode-extension-6.12.0\node_modules\vscode-languageclient\lib\node\main.js:150:22)
	at LanguageClient.handleConnectionError (c:\Users\userxyz\.vscode\extensions\contextmapper.context-mapper-vscode-extension-6.12.0\node_modules\vscode-languageclient\lib\common\client.js:1196:18)
```

Unsure what the problem is.

VS Code version is 1.96.2, running on Windows 11.

Please let me know if you need any more info!

**Comment by stefan-ka** [comment]
Hi @francoisvdv 

Sorry for the late response! What Java version have you installed?

Best regards,
Stefan

**Comment by francoisvdv** [comment]
Hi, haven't tried since december but it was the december version of the following:

```
$ java --version
openjdk 21.0.7 2025-04-15 LTS
OpenJDK Runtime Environment Microsoft-11369940 (build 21.0.7+6-LTS)
OpenJDK 64-Bit Server VM Microsoft-11369940 (build 21.0.7+6-LTS, mixed mode, sharing)
```

**Comment by eristocrates** [comment]
Hi @francoisvdv. I'm just a guy that was very excited to find this tool but ran into the same issue. I've been fighting for A couple of days but was finally able to make a breakthrough just last night. 

@stefan-ka can correct me if i'm wrong, but I believe the latest java you can use is 17, going off of the [v6.7.0 release notes](https://contextmapper.org/news/2022/12/02/v6.7.0-released/) linked from the very related [issue #290](https://github.com/ContextMapper/context-mapper-dsl/issues/290)

I actually had A whole host of various issues (i may suggest a separate enhancement to the docs later) but at the very least, I'd suggest starting with changing to a java 17 jdk. I personally found success with [\Eclipse Adoptium\jdk-17.0.15.6-hotspot](https://wingetgui.com/apps/EclipseAdoptium-Temurin-17-JRE)

**Comment by 0xBradock** [comment]
Hello,

I am also having trouble to launch the plugin from VSCode.
After installing the plugin I created a file `test.cml` with the following [content](https://github.com/ContextMapper/context-mapper-examples/blob/master/src/main/cml/insurance-example/Insurance-Example-Stage-1.cml).

Java:

```bash
❯ java --version
openjdk 21.0.8 2025-07-15
OpenJDK Runtime Environment (build 21.0.8+9-Ubuntu-0ubuntu124.04.1)
OpenJDK 64-Bit Server VM (build 21.0.8+9-Ubuntu-0ubuntu124.04.1, mixed mode, sharing)
```

The error message:

<img width="351" height="169" alt="Image" src="https://github.com/user-attachments/assets/0da54719-828b-4725-a50f-81f7d12dd8af" />

> I don't want to use the Gitpod because it would allow to read and write to public and private repos, which is odd.

Any help on how to generate the images are welcome.
I can also open a PR to fix the online doc.

Thanks,

**Comment by stefan-ka** [comment]
Hi @0xBradock 

Also Windows 11 I guess? 

It can't be JDK 21, because that works fine on my Linux setup. So it must be an issue with Windows; but I don't have I setup right now. I will create a Win11 VirtualBox and try to figure it out asap.

And yes, I totally agree with you on the Gitpod issue. We have to remove these links and the support from the website. I also don't use it anymore, since they want read-access to private repos. This is insane.

Best regards,
Stefan

**Comment by stefan-ka** [comment]
@0xBradock, since I am really not a Windows user... could you give some quick instructions how to do the setup exactly as you have it on your machine? I have a Win11 virtual machine now.

And, another question: Is this only for the Context Map Generator or do all generators not work? For example the PlantUML generator?

Best regards,
Stefan

**Comment by stefan-ka** [comment]
Maybe the CLI could be a temporary workaround to generate the diagrams: https://github.com/ContextMapper/context-mapper-cli

**Comment by 0xBradock** [comment]
I'll check the cli and get back to you.

> Hi [@0xBradock](https://github.com/0xBradock)
> 
> Also Windows 11 I guess?
> 
> It can't be JDK 21, because that works fine on my Linux setup. So it must be an issue with Windows; but I don't have I setup right now. I will create a Win11 VirtualBox and try to figure it out asap.
> 
> And yes, I totally agree with you on the Gitpod issue. We have to remove these links and the support from the website. I also don't use it anymore, since they want read-access to private repos. This is insane.
> 
> Best regards, Stefan

Hey, thanks for the swift reply.
I have a Windows alert because it's imposed at my workplace.
I am running VSCode from a WSL and also executing the commands from an Ubuntu WSL.
This answer your question?

**Comment by 0xBradock** [comment]
> Maybe the CLI could be a temporary workaround to generate the diagrams: https://github.com/ContextMapper/context-mapper-cli

I'll try it and get back to you, thanks

**Comment by 0xBradock** [comment]
> [@0xBradock](https://github.com/0xBradock), since I am really not a Windows user... could you give some quick instructions how to do the setup exactly as you have it on your machine? I have a Win11 virtual machine now.
> 
> And, another question: Is this only for the Context Map Generator or do all generators not work? For example the PlantUML generator?
> 
> Best regards, Stefan

I didn't try others. I'll do it and get back to you. Thanks
